// <auto-generated />
using System;
using AmtOrk.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmtOrkFull.Server.Migrations
{
    [DbContext(typeof(AmtOrkContext))]
    [Migration("20250620031141_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("AmtOrk.Server.Models.AmtClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.ToTable("AmtClass");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "Anti-Paladin"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "Archer"
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "Assassin"
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "Barbarian"
                        },
                        new
                        {
                            Id = 5,
                            ClassName = "Bard"
                        },
                        new
                        {
                            Id = 6,
                            ClassName = "Color"
                        },
                        new
                        {
                            Id = 7,
                            ClassName = "Druid"
                        },
                        new
                        {
                            Id = 8,
                            ClassName = "Healer"
                        },
                        new
                        {
                            Id = 9,
                            ClassName = "Monk"
                        },
                        new
                        {
                            Id = 10,
                            ClassName = "Monster"
                        },
                        new
                        {
                            Id = 11,
                            ClassName = "Paladin"
                        },
                        new
                        {
                            Id = 12,
                            ClassName = "Peasant"
                        },
                        new
                        {
                            Id = 13,
                            ClassName = "Reeve"
                        },
                        new
                        {
                            Id = 14,
                            ClassName = "Scout"
                        },
                        new
                        {
                            Id = 15,
                            ClassName = "Warrior"
                        },
                        new
                        {
                            Id = 16,
                            ClassName = "Wizard"
                        });
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreditDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditKingdomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrkUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrkUserId");

                    b.ToTable("Credit");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KingdomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LandId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.HasIndex("LandId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChampionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GMRId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KingdomDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("KingdomIconPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("KingdomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonarchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimeMinisterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("GMRId");

                    b.HasIndex("KingdomName")
                        .IsUnique();

                    b.HasIndex("MonarchId");

                    b.HasIndex("PrimeMinisterId");

                    b.HasIndex("RegentId");

                    b.ToTable("Kingdom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0038.jpg",
                            KingdomName = "13 Roads"
                        },
                        new
                        {
                            Id = 2,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0018.jpg",
                            KingdomName = "Kingdom of Desert Winds"
                        },
                        new
                        {
                            Id = 3,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0014.jpg",
                            KingdomName = "The Celestial Kingdom"
                        },
                        new
                        {
                            Id = 4,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0022.jpg",
                            KingdomName = "The Empire of Rivermoor"
                        },
                        new
                        {
                            Id = 5,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0003.jpg",
                            KingdomName = "The Empire of the Iron Mountains"
                        },
                        new
                        {
                            Id = 6,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0008.jpg",
                            KingdomName = "The Freeholds of Amtgard"
                        },
                        new
                        {
                            Id = 7,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0016.jpg",
                            KingdomName = "The Kingdom of Blackspire"
                        },
                        new
                        {
                            Id = 8,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0007.jpg",
                            KingdomName = "The Kingdom of Burning Lands"
                        },
                        new
                        {
                            Id = 9,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0017.jpg",
                            KingdomName = "The Kingdom of Crystal Groves"
                        },
                        new
                        {
                            Id = 10,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0012.jpg",
                            KingdomName = "The Kingdom of Dragonspine"
                        },
                        new
                        {
                            Id = 11,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0004.jpg",
                            KingdomName = "The Kingdom of Goldenvale"
                        },
                        new
                        {
                            Id = 12,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0005.jpg",
                            KingdomName = "The Kingdom of Neverwinter"
                        },
                        new
                        {
                            Id = 13,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0020.jpg",
                            KingdomName = "The Kingdom of Northern Lights"
                        },
                        new
                        {
                            Id = 14,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0036.jpg",
                            KingdomName = "The Kingdom of Northreach"
                        },
                        new
                        {
                            Id = 15,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0027.jpg",
                            KingdomName = "The Kingdom of Polaris"
                        },
                        new
                        {
                            Id = 16,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0019.jpg",
                            KingdomName = "The Kingdom of Tal Dagore"
                        },
                        new
                        {
                            Id = 17,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0006.jpg",
                            KingdomName = "The Kingdom of the Emerald Hills"
                        },
                        new
                        {
                            Id = 18,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0011.jpg",
                            KingdomName = "The Kingdom of the Golden Plains"
                        },
                        new
                        {
                            Id = 19,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0031.jpg",
                            KingdomName = "The Kingdom of the Nine Blades"
                        },
                        new
                        {
                            Id = 20,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0010.jpg",
                            KingdomName = "The Kingdom of the Rising Winds"
                        },
                        new
                        {
                            Id = 21,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0001.jpg",
                            KingdomName = "The Kingdom of the Wetlands"
                        },
                        new
                        {
                            Id = 22,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0025.jpg",
                            KingdomName = "The Kingdom of Viridian Outlands"
                        },
                        new
                        {
                            Id = 23,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0021.jpg",
                            KingdomName = "The Kingdom of Westmarch"
                        },
                        new
                        {
                            Id = 24,
                            KingdomIconPath = "https://ork.amtgard.com/assets/heraldry/kingdom/0024.jpg",
                            KingdomName = "The Kingdom of Winters Edge"
                        });
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Land", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChampionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GMRId")
                        .HasColumnType("TEXT");

                    b.Property<int>("KingdomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LandDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LandIconPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonarchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimeMinisterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("GMRId");

                    b.HasIndex("KingdomId");

                    b.HasIndex("MonarchId");

                    b.HasIndex("PrimeMinisterId");

                    b.HasIndex("RegentId");

                    b.ToTable("Land");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.OrkUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CorporaQualified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeraldryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWaivered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ParkMemberSince")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PasswordExpires")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReeveQualified")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrkUser");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Credit", b =>
                {
                    b.HasOne("AmtOrk.Server.Models.OrkUser", null)
                        .WithMany("Credits")
                        .HasForeignKey("OrkUserId");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Event", b =>
                {
                    b.HasOne("AmtOrk.Server.Models.Kingdom", null)
                        .WithMany("KingdomEvents")
                        .HasForeignKey("KingdomId");

                    b.HasOne("AmtOrk.Server.Models.Land", null)
                        .WithMany("LandEvents")
                        .HasForeignKey("LandId");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Kingdom", b =>
                {
                    b.HasOne("AmtOrk.Server.Models.OrkUser", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId");

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "GMR")
                        .WithMany()
                        .HasForeignKey("GMRId");

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "Monarch")
                        .WithMany()
                        .HasForeignKey("MonarchId");

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "PrimeMinister")
                        .WithMany()
                        .HasForeignKey("PrimeMinisterId");

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "Regent")
                        .WithMany()
                        .HasForeignKey("RegentId");

                    b.Navigation("Champion");

                    b.Navigation("GMR");

                    b.Navigation("Monarch");

                    b.Navigation("PrimeMinister");

                    b.Navigation("Regent");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Land", b =>
                {
                    b.HasOne("AmtOrk.Server.Models.OrkUser", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId");

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "GMR")
                        .WithMany()
                        .HasForeignKey("GMRId");

                    b.HasOne("AmtOrk.Server.Models.Kingdom", null)
                        .WithMany("Lands")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "Monarch")
                        .WithMany()
                        .HasForeignKey("MonarchId");

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "PrimeMinister")
                        .WithMany()
                        .HasForeignKey("PrimeMinisterId");

                    b.HasOne("AmtOrk.Server.Models.OrkUser", "Regent")
                        .WithMany()
                        .HasForeignKey("RegentId");

                    b.Navigation("Champion");

                    b.Navigation("GMR");

                    b.Navigation("Monarch");

                    b.Navigation("PrimeMinister");

                    b.Navigation("Regent");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Kingdom", b =>
                {
                    b.Navigation("KingdomEvents");

                    b.Navigation("Lands");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.Land", b =>
                {
                    b.Navigation("LandEvents");
                });

            modelBuilder.Entity("AmtOrk.Server.Models.OrkUser", b =>
                {
                    b.Navigation("Credits");
                });
#pragma warning restore 612, 618
        }
    }
}
